spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/belvo_poc
    username: postgres
    password: ${BELVO_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secretKey: ${BELVO_JWT_SECRET_KEY}
