spring:
  datasource:
    url: ${DB_URL}
    username: postgres
    password: ${BELVO_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
jwt:
  secretKey: ${BELVO_JWT_SECRET_KEY}
api:
  belvoApiBaseUrl: ${BELVO_API_BASE_URL}
  belvoApiId: ${BELVO_API_ID}
  belvoApiPassword: ${BELVO_API_PASSWORD}

